name: Build Shibboleth Nginx Module for Debian Trixie

on:
  push:
    branches:
      - main
    paths:
      - scripts/debian/trixie/*
      - .github/workflows/debian-trixie-build.yml
  schedule:
    - cron: '10 2 * * *'
  workflow_dispatch:
    inputs:
      force_rebuild_shibboleth_modules:
        description: 'Force rebuild Nginx Shibboleth modules'
        required: false
        default: false
        type: boolean

jobs:
  debian-trixie-docker-build:
    name: Build packages for Debian Trixie
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          lfs: true
          sparse-checkout: |
            repo/debian/trixie
            scripts/debian/trixie
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Build Shibboleth Nginx modules for Debian Trixie
        run: >
          docker run --rm
          -v ${{ github.workspace }}/repo/debian/trixie:/repo
          -v ${{ github.workspace }}/scripts/debian/trixie:/scripts:ro
          -e FORCE_REBUILD_SHIBBOLETH_MODULES=$FORCE_REBUILD_SHIBBOLETH_MODULES
          debian:trixie
          /bin/bash /scripts/cron-build-shib-nginx-mod.sh
        env:
          FORCE_REBUILD_SHIBBOLETH_MODULES: ${{ inputs.force_rebuild_shibboleth_modules }}

      - name: Commit build package
        run: |
          git config --global user.name 'GitHub build bot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          (git add repo/debian/trixie/pool/non-free/*.deb && git commit -m "[automated] Debian Trixie package added" && git push) || echo "No new packages found, skip updating."
