name: Udpate Debian Trixie repo

on:
  push:
    branches:
      - main
    paths:
      - repo/debian/trixie/pool/non-free/*.deb
      - .github/workflows/debian-trixie-update-repo.yml
  workflow_dispatch:
    inputs:
      force_recreate_repo:
        description: 'Force recreate Debian repository'
        required: false
        type: boolean
        default: false

jobs:
  debian-trixie-update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          lfs: true
          sparse-checkout: |
            repo/debian/trixie
            scripts/debian/trixie
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Update Debian Trixie repository
        run: >
          docker run --rm
          -v ${{ github.workspace }}/repo/debian/trixie:/repo
          -v ${{ github.workspace }}/scripts/debian/trixie:/scripts:ro
          -e FORCE_RECREATE_REPO=$FORCE_RECREATE_REPO
          -e GPG_SIGNING_KEY=$GPG_SIGNING_KEY
          debian:trixie
          /bin/bash /scripts/update-repo.sh
        env:
          FORCE_RECREATE_REPO: ${{ inputs.force_recreate_repo }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Commit Debian Trixie repo
        run: |
          git config --global user.name 'GitHub build bot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          (git add repo/debian/trixie/dists/trixie/Release* && git add repo/debian/trixie/dists/trixie/InRelease && git add repo/debian/trixie/dists/trixie/non-free/binary-amd64/Packages* && git commit -m "[automated] Debian Trixie repo updated" && git push) || echo "No new packages found, skip updating."
