name: Sign RHEL10 RPM repo

on:
  workflow_dispatch:

jobs:
  rhel10-sign-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v6
        with:
          lfs: true
          sparse-checkout: |
            repo/rhel/10
            scripts/rhel/10
          ssh-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Sign RHEL10 RPM repository
        run: >
          docker run --rm
          -v ${{ github.workspace }}/repo/rhel/10:/repo
          -v ${{ github.workspace }}/scripts/rhel/10:/scripts:ro
          -e GPG_SIGNING_KEY=$GPG_SIGNING_KEY
          rockylinux:10
          /bin/bash /scripts/sign-packages-and-repo.sh
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Commit RHEL10 RPM repo
        run: |
          git config --global user.name 'GitHub build bot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          (git add repo/rhel/10/*.rpm && git add repo/rhel/10/repodata && git commit -m "[automated] RHEL10 RPM repo signed" && git push) || echo "No new packages found, skip updating."
